### ISSUE TITLE
mplot bug?

### ISSUE THREAD

**Issue by bgpantojar** [NumSoftware/Amaru.jl#36] opened 2022-09-01 14:58 UTC
Hello,

I was wondering if the mplot() function intentionally does not show any plot when it is given the "name.svg" variable. I would like to show the plot and save at the same time the mesh. WIth: `mplot(block, "block.svg", markers=true)` just the figure is saved.

Best,
Bryan

**Comment by RaulDurand** [comment] 2022-09-01 15:34
This behavior is by design. I believe that the most common use of mplot is to save the plot. 
This is useful when many files are saved in a single script without the need of interacting with the plot windows.
In your case, I recommend using an external pdf viewer that updates the view when the file changes, e.g. evince, qpdfview, okular, etc.
Is there any specific use case to view and save the file at the same time?

**Comment by bgpantojar** [comment] 2022-09-01 15:51
Understand. In the case I want to check what is producing the script when writing it (for instance following Amaru's tutorial at vscode). The walk around I am doing so far is just writing `mplot(block, markers=true)`. But for me make sense the default set up.

**Comment by bgpantojar** [comment] 2022-09-01 16:55
I found a possible bug in the cplot() function now. Check the fig please. I did not find any example inside the test files. It comes because it does not recognize the filename variable. When deleting that line, it works.


![Screenshot from 2022-09-01 18-53-06](https://user-images.githubusercontent.com/35929939/187970100-e6dbf8f6-8aad-467e-a76e-f929317b9f7b.png)

**Comment by RaulDurand** [comment] 2022-09-02 21:39
I am closing now. Feel free to reopen de issue as needed.

**Closed by RaulDurand** 2022-09-02 21:39 UTC
